# Generated by Django 4.0.2 on 2022-05-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
